theme: minima
title: Andy Glover
description: Aerospace • Autonomy • Robotics Engineering

minima:
  custom_css:
    - assets/css/custom.css

header_pages:
  - index.md
  - projects/autonomy.md
  - projects/water-channel.md
  - resume.md
  - contact.md
