theme: minima
title: Andy Glover
description: Aerospace • Autonomy • Robotics Engineering

header_pages:
  - index.md
  - projects/autonomy.md
  - projects/water-channel.md
  - resume.md
  - contact.md
